# services:
#   mongo:
#     image: mongo:latest
#     container_name: mongo
#     restart: always
#     environment:
#       - MONGO_INITDB_ROOT_USERNAME=admin
#       - MONGO_INITDB_ROOT_PASSWORD=admin
#     ports:
#       - 27017:27017
#     volumes:
#       - ./mongo-data:/data/db
version: '3'

services:
  top.api:
    image: search-appa:latest
    container_name: search-appa
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./.env:/opt/app/.env
